import Head from "next/head";
import Image from 'next/image'
import { Inter } from "@next/font/google";
//import styles from '@/styles/Home.module.css'
import Container from "@/components/ui/Container";
import { useState } from "react";
import Sliderr from "@/components/ui/Sliderr";
import Slider1 from "@/components/ui/Slider1";
//import YouTube from "react-youtube";
const inter = Inter({ subsets: ["latin"] });




export default function Home() {
  const [Faq1, setFaq1] = useState(false);
  const [Faq2, setFaq2] = useState(false);
  const [Faq3, setFaq3] = useState(false);
  const [Faq4, setFaq4] = useState(false);
  const [Faq5, setFaq5] = useState(false);
  const [Faq6, setFaq6] = useState(false);
  const [Faq7, setFaq7] = useState(false);
  const [Faq8, setFaq8] = useState(false);
  const [Faq9, setFaq9] = useState(false);
  const [Faq10, setFaq10] = useState(false);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.icon" />
      </Head>
      <main>
        <div className="  w-full h-auto bg-pink-50 sm:px-0 px-1  ">
          <div className=" w-full md:flex   ">
            <div className="md:w-[50%] w-full">
              <div className="w-full">
                <Image
                  src="/poster1.png"
                  fill
                  alt="poster"
                  className="custom_img"
                />
              </div>
            </div>

            <div className="md:w-[50%] w-full ">
              <iframe
                src="https://www.youtube.com/embed/pxOu8gO5mTI"
                frameborder
                autoplay
                // clipboard-write
                encrypted-media="true"
                // gyroscope
                //picture-in-picture
                web-share
                allowFullScreen
                className="custom_img"
              />
            </div>
          </div>
        </div>
        {/*==========================================Smartest Payment Gateway for Car Rentals ==================================== */}

        <div className="  mt-[20px] mx-3 p-5    bg-background bg-center bg-cover bg-no-repeat">
          <Container>
            <div className="text-center md:ml-0 ml-2 sm:p-0 md:p-6 md:text-3xl text-lg  font-bold leading-1 font-nova">
              Smartest Payment Gateway for
              <span className="text-red-600"> Car Rentals</span>
            </div>

            <div className="   grid grid-cols-3 lg:gap-44 md:gap-3 sm:gap-6 gap-12 items-center  mx-7  mt-5 text-darkGray font-nova lg:text-2xl md:text-lg sm:text-sm text-[10px] md:leading-7 justify-between">
              <div className=" flex-col justify-between  ">
                <div className="  ">
                  <Image
                    src="./onlineRegistration.svg"
                    alt="onlineRegistration"
                    fill
                    className="custom_img"
                  />
                </div>
                <div className=" text-center">Sign Up for Free</div>
              </div>
              <div className=" flex-col justify-between items-center ">
                <div className=" ">
                  <Image
                    src="/getApplication.webp"
                    alt="getApplication"
                    fill
                    className="custom_img"
                  />
                </div>
                <div className=" text-center  ">
                  Get Application Approval
                  <span className="ml-1 ">within 24 hours</span>
                </div>

                {/* <div className="bg-[#ff0000] items-center  my-3  text-white hover:text-[#ff0000] hover:bg-white hover:border border-2  border-[#ff0000] w-20 rounded p-2 text-center mt-5 ml-[26%]">
                  <span className=" ">Sign Up</span>
                </div> */}
              </div>

              <div className="flex-col  gap-24">
                <div className="  ">
                  <Image
                    src="/RecevingPayments.webp"
                    alt="RecevingPayments"
                    fill
                    className="custom_img"
                  />
                </div>
                <div className="text-center">Start Receiving Payments</div>
              </div>
            </div>

            <div className="bg-[#ff0000] font-sans md:text-[22px] text-[12px] font-normal cursor-pointer  text-white hover:text-[#ff0000] text-xl hover:bg-white hover:border border-2 table  border-[#ff0000] md:w-24 sm:w-20 w-14 rounded  text-center mt-5 lg:ml-[46%] ml-[44%]">
              <span className="p-1 ">Sign Up</span>
            </div>
          </Container>
        </div>

        {/*============================================================== SLIDER ===================================== */}

        <div className="   mt-5 sm:mx-3 mx-6 ">
          <Slider1 />
        </div>

        {/*=============================================== content ===================================================*/}
        <div className="md:mt-8 ">
          <Container>
            <div>
              <div className="md:flex gap-5  ">
                <div className="md:w-[50%] w-full md:p-4 sm:p-2 sm:pr-0 pl-8 pr-8">
                  <span className="md:text-[22px] text-[16px] text-darkGray font-serif font-semibold">
                    Going Global?
                  </span>
                  <p className=" md:text-[22px] text-[16px] text-darkGray font-serif font-semibold">
                    We got your business covered
                  </p>
                  <span className="w-10 text-darkGray text-base font-light  text-[16px] text-center">
                    With MyridePay, geography will be history. To cater to
                    online businesses with global reach, our secure and seamless
                    global payment gateway can support customers by facilitating
                    payments through multiple payment options like American
                    Express, MasterCard, Visa, mada, SADAD, STC Pay, OmanNet and
                    many more.
                  </span>
                </div>

                <div className=" w-full md:flex md:p-3  flex-col  md:w-[50%] sm:px-30 px-12 mt-8    text-[13px] font-sans text-darkGray">
                  <div className=" grid md:grid-cols-2 grid-cols-1 lg:gap-24 md:gap-14 gap-2 justify-between    ">
                    <div className="md:flex  flex gap-4 ">
                      <Image
                        src="./Tick.svg"
                        alt="tick"
                        width={20}
                        height={10}
                        className="relative  "
                      />
                      <span className="w-full ">Easy Monthly Installments</span>
                    </div>
                    <div className="md:flex  flex gap-4 md:mt-0 mt-2">
                      <Image
                        src="./Tick.svg"
                        alt="tick"
                        width={20}
                        height={10}
                        className="relative   md:mt-0 mt-2"
                      />
                      <span className="mt-2">Payment Tokenization</span>
                    </div>
                  </div>
                  <div className="grid md:grid-cols-2 grid-cols-1 md:gap-24 gap-2 justify-between ">
                    <div className="md:flex  flex gap-4 mt-2">
                      <Image
                        src="./Tick.svg"
                        alt="tick"
                        width={20}
                        height={10}
                        className="relative  md:mt-0 mt-4"
                      />
                      <span className=" md:mt-0  mt-4">Subscriptions</span>
                    </div>
                    <div className="md:flex  flex gap-4 mt-2">
                      <Image
                        src="./Tick.svg"
                        alt="tick"
                        width={20}
                        height={10}
                        className="relative  md:mt-0 "
                      />
                      <span className="">Recurring Payments</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </Container>
        </div>
        {/*=================================== Platform to Align Your Car Rental Collections Once and For All============================ */}
        <div className="   w-full h-auto mt-5">
          <Container>
            <div className="w-full  md:flex flex-shrink-0 md:p-4 md:gap-7 mt-5 text-[16px] font-sans ">
              <div className="md:w-[50%] w-full md:p-0 sm:p-2 p-8 ">
                <span className="md:text-[25px] text-[16px] leading-3 font-sans text-darkGray    font-semibold ">
                  Platform to Align Your Car Rental Collections Once and For All
                </span>

                <div className="md:w-[456px] w-full  text-darkGray ">
                  In any business platform, secure payments are the biggest
                  concern. Car rental industry in UAE has vast prospects, and
                  with that comes a concern to keep an established payment
                  gateway for the renters all around the world. MyRide being the
                  devotees for cars wanted an easy process of receiving,
                  converting and tracking the payments received by the renters
                  all around the world. Hence, MyRidePay was born. So no matter
                  what kind of car rental industry you have, let us handle your
                  payment gateway and be free of excessive processes to handle
                  the payments.
                </div>
              </div>
              <div className="w-[50%] mx-auto md:pl-[13%]">
                <div className="  w-[200px] xs:w-[288px] md:w-[240px] h-[200px] xs:h-[310px] md:h-[280px]  ">
                  <Image
                    src="/carCollction.webp"
                    alt="car"
                    fill
                    className="custom_img"
                  />
                </div>
              </div>
            </div>
          </Container>
        </div>
        {/*============================== Why Choose MyRidePay for a Car Rental Gateway? =================================*/}
        <div className="md:flex  w-full h-auto mt-5 pb-4">
          <Container>
            <div className="  w-full md:flex md:flex-shrink-0  md:gap-20  lg:mt-5  font-sans">
              <div className="w-[50%] mx-auto md:pr-0 pr-5 ">
                <div className=" lg:mt-0 mt-3 md:pr-8  flex-shrink-0  md:w-[511px] sm:w-[350px] w-[240px] md:h-[507px] xs:h-[380px] h-[230px]">
                  <Image
                    src="/chooseUs.webp"
                    alt="choose us"
                    fill
                    className="custom_img"
                  />
                </div>
              </div>
              <div className=" md:w-[50%] w-full text-left  md:p-4 sm:p-4 p-8">
                <span className=" md:text-[25px] text-[16px] text-left leading-3  font-sans font-semibold text-darkGray">
                  Why Choose MyRidePay for a Car Rental Gateway?
                </span>

                <div className="text-[16px] items-center  text-darkGray w-full">
                  To provide car rental companies with the most secure payment
                  gateway, we have partnered with PayTabs. PayTabs is one of the
                  leading payment gateway providers for every industry. Our
                  years of experience in the automobile industry and PayTabs
                  experience combined can solve all of your payment problems.
                  <li>
                    Accept payments from anywhere in the world with multiple
                    alternative payment options, our payment gateway makes car
                    rental for your customers hassle-free which subsequently
                    helps you to grow your business.
                  </li>
                  <li>
                    Payment security and fraud prevention are the main focus of
                    this venture. We keep your customers data secure, so they
                    can rely on you for your services.
                  </li>
                  <li>
                    Boost your processing speed with this payment platform, more
                    reliability and better acceptance rates.
                  </li>
                  <li>
                    You will have a personal and dedicated account team and live
                    transaction monitoring option for closer accessibility.
                  </li>
                  <li>
                    Simple website integrations with API solutions, SDK, HTTPS
                    redirection and secure hosting.
                  </li>
                  <li>
                    Quickly receive access to the amount paid by your customers.
                  </li>
                  <li>
                    Accept payments securely and immediately via Visa and
                    Mastercard and we will settle your sales automatically to
                    your bank account.
                  </li>
                  <div className="  text-[13px] font-serif px-[3px] py-[15px]  bg-[#bf0000] text-white text-xs  font-bold text-center lg:w-[60%] md:w-[80%] w-[90%] md:ml-0 ml-3 p-2 rounded mt-6 ">
                    Checkout Our Awesome Packages
                  </div>
                </div>
              </div>
            </div>
          </Container>
        </div>
        {/*================================================== Services Slider ============================================ */}

        <div className="  ">
          <p className="text-center text-4xl text-[2rem] font-normal ">
            Services
          </p>
          <div className=" mx-5 ">
            <Sliderr />
          </div>
        </div>

        {/*================================================== FAQs =================================================== */}
        <div className=" mt-8 ">
          <Container>
            <div className="w-full justify-between md:p-4 sm:p-0 p-8   ">
              <span className="text-4xl text-[#212529] text-[24px] indent-[22px] font-raleway px-6 ">
                FAQs
              </span>
              <div className="md:flex justify-between w-full mt-5">
                <div className="md:w-[50%] w-full bg-gray-100">
                  <div className="bg-white w-full">
                    <div className="flex gap-3 text-[#0e314c] font-medium font-raleway text-[16px] items-center">
                      {Faq1 ? (
                        <div
                          className="w-[10%] bg-[#ff0000] p-2 h-[20%] text-center text-white font-bold cursor-pointer"
                          onClick={() => setFaq1(false)}
                        >
                          -
                        </div>
                      ) : (
                        <div
                          className="w-[10%] bg-[#ff0000] p-2 h-[20%] text-center text-white font-bold cursor-pointer"
                          onClick={() => {
                            setFaq1(true);
                            setFaq2(false);
                            setFaq3(false);
                            setFaq4(false);
                            setFaq5(false);
                          }}
                        >
                          +
                        </div>
                      )}

                      <div className="w-[100%]">
                        When Can You Integrate with MyridePay Payment Gateway?
                      </div>
                    </div>

                    {Faq1 ? (
                      <div className="flex border-t-2 pt-3">
                        <div className="px-8 font-normal text-[16px] font-sans text-[#212529]">
                          MyridePay offers a test before you go live. You can
                          register online and test our services. Once you are
                          satisfied, you can integrate the gateway and go live.
                        </div>
                      </div>
                    ) : (
                      " "
                    )}
                  </div>
                  <div>
                    <div className="bg-white ">
                      <div className="flex  gap-3 mt-5 text-[#0e314c] font-medium font-raleway text-[16px] items-center">
                        {Faq2 ? (
                          <div
                            className="w-[10%] bg-[#ff0000] p-2 h-[20%] text-center text-white font-bold cursor-pointer"
                            onClick={() => setFaq2(false)}
                          >
                            -
                          </div>
                        ) : (
                          <div
                            className="w-[10%] bg-[#ff0000] p-2 h-[20%] text-center text-white font-bold cursor-pointer"
                            onClick={() => {
                              setFaq1(false),
                                setFaq2(true),
                                setFaq3(false),
                                setFaq4(false),
                                setFaq5(false);
                            }}
                          >
                            +
                          </div>
                        )}
                        <div className="">What is a Payment Gateway?</div>
                      </div>

                      {Faq2 ? (
                        <div className="flex border-t-2 pt-3">
                          <div className="px-8 font-normal text-[16px] font-sans text-[#212529]">
                            Whenever someone makes a payment through their
                            credit card, the information is sent to the
                            cardholder’s account to check if the transaction is
                            allowed or not. In an E-commerce setting, this
                            process is done via Payment Gateway. Every company
                            who wishes to accept credit cards require a safe
                            portal through which the transactions can pass.
                            MyridePay offers a secure portal for online payments
                            for car rental companies.
                          </div>
                        </div>
                      ) : (
                        " "
                      )}
                    </div>
                    <div className="bg-white">
                      <div className="flex  gap-3 mt-5 text-[#0e314c] font-medium font-raleway text-[16px] items-center">
                        {Faq3 ? (
                          <div
                            className="w-[10%] bg-[#ff0000] p-2 h-[20%] text-center text-white font-bold cursor-pointer"
                            onClick={() => setFaq3(false)}
                          >
                            -
                          </div>
                        ) : (
                          <div
                            className="w-[10%]  bg-[#ff0000] p-2 h-[20%] text-center text-white font-bold cursor-pointer"
                            onClick={() => {
                              setFaq1(false),
                                setFaq2(false),
                                setFaq3(true),
                                setFaq4(false),
                                setFaq5(false);
                            }}
                          >
                            +
                          </div>
                        )}
                        <div className="">
                          How Long Does It Take To Integrate MyridePay Payment
                          Gateway?
                        </div>
                      </div>

                      {Faq3 ? (
                        <div className="flex border-t-2 pt-3">
                          <div className="px-8 font-normal text-[16px] font-sans text-[#212529]">
                            The integration process of MyridePay Payment Gateway
                            can take anywhere between 24 to 48 hours.
                          </div>
                        </div>
                      ) : (
                        " "
                      )}
                    </div>
                  </div>

                  <div className="bg-white">
                    <div className="flex gap-3  mt-5 text-[#0e314c] font-medium font-raleway text-[16px] items-center">
                      {Faq4 ? (
                        <div
                          className="w-[10%] bg-[#ff0000] p-2 h-[20%] text-center text-white font-bold cursor-pointer"
                          onClick={() => setFaq4(false)}
                        >
                          -
                        </div>
                      ) : (
                        <div
                          className="w-[10%] bg-[#ff0000] p-2 h-[20%] text-center text-white font-bold cursor-pointer "
                          onClick={() => {
                            setFaq1(false),
                              setFaq2(false),
                              setFaq2(false),
                              setFaq3(false),
                              setFaq4(true),
                              setFaq5(false);
                          }}
                        >
                          +
                        </div>
                      )}
                      <div className="">
                        What Do I Need to Start Accepting Credit Cards?
                      </div>
                    </div>

                    {Faq4 ? (
                      <div className="flex  border-t-2 pt-3">
                        <div className="px-8 font-normal text-[16px] font-sans text-[#212529]">
                          You need a working online website for renting cars.
                          Once we have verified your credentials, you will be
                          provided with a login and password bank account with
                          our affiliated bank.
                        </div>
                      </div>
                    ) : (
                      " "
                    )}
                  </div>

                  <div className="">
                    <div className="bg-white">
                      <div className="flex gap-2 mt-5 text-[#0e314c] font-medium font-raleway text-[16px] items-center">
                        {Faq5 ? (
                          <div
                            className="w-[10%] bg-[#ff0000] p-2 h-[20%] text-center text-white font-bold cursor-pointer"
                            onClick={() => setFaq5(false)}
                          >
                            -
                          </div>
                        ) : (
                          <div
                            className="w-[10%] bg-[#ff0000] p-2 h-[20%] text-center text-white font-bold cursor-pointer "
                            onClick={() => {
                              setFaq1(false),
                                setFaq1(false),
                                setFaq2(false),
                                setFaq3(false),
                                setFaq4(false),
                                setFaq5(true);
                            }}
                          >
                            +
                          </div>
                        )}
                        <div className="">
                          What Kind of Credit/Debit Cards are Accepted?
                        </div>
                      </div>

                      {Faq5 ? (
                        <div className="flex justify-between border-t-2 pt-3 ">
                          <div className="px-8 font-normal text-[16px] font-sans text-[#212529]">
                            You will be able to accept major credit/debit cards
                            from MasterCard, Visa, American Express* at this
                            moment. We will be adding more card processors
                          </div>
                        </div>
                      ) : (
                        " "
                      )}
                    </div>
                  </div>
                </div>

                {/*=============================================== FAQs 2nd part ===========================================================*/}

                <div className="md:w-[50%] bg-gray-100 w-full md:mt-0 mt-5">
                  <div>
                    <div className="bg-white">
                      <div className="flex gap-3 text-[#0e314c] font-medium font-raleway text-[16px] items-center">
                        {Faq6 ? (
                          <div
                            className="w-[10%] bg-[#ff0000] p-2 h-[20%] text-center text-white font-bold cursor-pointer"
                            onClick={() => setFaq6(false)}
                          >
                            -
                          </div>
                        ) : (
                          <div
                            className="w-[10%] bg-[#ff0000] p-2 h-[20%] text-center text-white font-bold cursor-pointer "
                            onClick={() => {
                              setFaq6(true),
                                setFaq7(false),
                                setFaq8(false),
                                setFaq9(false),
                                setFaq10(true);
                            }}
                          >
                            +
                          </div>
                        )}

                        <div className="">
                          Do I Need Another Software for Credit Card Payments?
                        </div>
                      </div>

                      {Faq6 ? (
                        <div className="flex border-t-2 pt-3 ">
                          <div className=" px-7 font-normal text-[16px] font-sans text-[#212529]">
                            Our system works with all the operating systems and
                            mobile operating systems, so you don’t have to plug
                            in any other software.Once you have created an
                            account with us, we will provide you with simple
                            coding and you’re done.
                          </div>
                        </div>
                      ) : (
                        " "
                      )}
                    </div>
                  </div>

                  <div>
                    <div className="bg-white">
                      <div className="flex gap-3 mt-5 text-[#0e314c] font-medium font-raleway text-[16px] items-center">
                        {Faq7 ? (
                          <div
                            className="w-[10%] bg-[#ff0000] p-2 h-[20%] text-center text-white font-bold cursor-pointer"
                            onClick={() => setFaq7(false)}
                          >
                            -
                          </div>
                        ) : (
                          <div
                            className="w-[10%] bg-[#ff0000] p-2 h-[20%] text-center text-white font-bold cursor-pointer "
                            onClick={() => {
                              setFaq6(false),
                                setFaq7(true),
                                setFaq8(false),
                                setFaq9(false),
                                setFaq10(false);
                            }}
                          >
                            +
                          </div>
                        )}
                        <div className="">
                          Can I Get Details of the Payments?
                        </div>
                      </div>

                      {Faq7 ? (
                        <div className="flex border-t-2 pt-3 ">
                          <div className="px-8 font-normal text-[16px] font-sans text-[#212529]">
                            Details of transactions are available 24/7 in your
                            account. You can check them anytime.
                          </div>
                        </div>
                      ) : (
                        " "
                      )}
                    </div>
                  </div>

                  <div>
                    <div className="bg-white">
                      <div className="flex gap-3 mt-5 text-[#0e314c] font-medium font-raleway text-[16px] items-center">
                        {Faq8 ? (
                          <div
                            className="w-[15%] bg-[#ff0000] p-2 h-[20%] text-center text-white font-bold cursor-pointer"
                            onClick={() => setFaq8(false)}
                          >
                            -
                          </div>
                        ) : (
                          <div
                            className="w-[15%] bg-[#ff0000] p-2 h-[20%] text-center text-white font-bold cursor-pointer "
                            onClick={() => {
                              setFaq6(false),
                                setFaq7(false),
                                setFaq8(true),
                                setFaq9(false),
                                setFaq10(false);
                            }}
                          >
                            +
                          </div>
                        )}
                        <div className="">
                          What Documents do I require to get a Payment
                          Gateway?an I have multiple activities in a single
                          feature?
                        </div>
                      </div>

                      {Faq8 ? (
                        <div className="flex  border-t-2 pt-3 text-[#0e314c] font-medium font-raleway text-[16px] items-center ">
                          <div className="px-8 font-normal text-[16px] font-sans text-[#212529]">
                            To activate your application, MyridePay requires
                            clear scanned copy the following documents:
                            <li>
                              Personal IDs issued by the Government of Your Car
                              Rental Business owner and partner(s) if any.
                            </li>
                            <li>
                              Government Issued Business License/Commercial
                              Registration (CR).
                            </li>
                            <li>
                              Company’s Bank Statement (3 months) on the Bank’s
                              official letterhead, containing complete account
                              information IBAN, account number, beneficiary name
                              etc.
                            </li>
                            <li>
                              Your logo will be required after signing up when
                              you have started using the payment gateway.
                            </li>
                            <li>
                              Proof of Address (eg: Rental lease, Electricity
                              Bill)
                            </li>
                            <li>Rental Company’s Terms and Conditions.</li>
                            <li>MOA / if Applicable.</li>
                            Further documentation can be demanded to help
                            demonstrate the financial stability and continuity
                            of the business. Note: Upload clear copies of the
                            requested documents. State required details as
                            accurately as possible to avoid delays in the
                            approval process. Contact us for further assistance.
                          </div>
                        </div>
                      ) : (
                        " "
                      )}
                    </div>
                  </div>

                  <div>
                    <div className="bg-white">
                      <div className="flex gap-3 mt-5 text-[#0e314c] font-medium font-raleway text-[16px] items-center">
                        {Faq9 ? (
                          <div
                            className="w-[10%] bg-[#ff0000] p-2 h-[20%] text-center text-white font-bold cursor-pointer"
                            onClick={() => setFaq9(false)}
                          >
                            -
                          </div>
                        ) : (
                          <div
                            className="w-[10%] bg-[#ff0000] p-2 h-[20%] text-center text-white font-bold cursor-pointer "
                            onClick={() => {
                              setFaq6(false),
                                setFaq7(false),
                                setFaq8(false),
                                setFaq9(true),
                                setFaq10(false);
                            }}
                          >
                            +
                          </div>
                        )}
                        <div className="">
                          Why is My Payment Gateway Taking Long to be Live?
                        </div>
                      </div>

                      {Faq9 ? (
                        <div className="flex   border-t-2 pt-3 ">
                          <div className="px-8 font-normal text-[16px] font-sans text-[#212529]">
                            Here are some reasons for delays in your Account.
                            <li>
                              There is an issue with the validity of the
                              documents.
                            </li>
                            <li>
                              We require additional documentation regarding your
                              establishment.
                            </li>
                            <li>
                              There might be a delay in the bank’s process.
                            </li>
                            <li>The application requires special approval.</li>
                          </div>
                        </div>
                      ) : (
                        " "
                      )}
                    </div>
                  </div>

                  <div>
                    <div className="bg-white">
                      <div className="flex gap-3 mt-5 text-[#0e314c] font-medium font-raleway text-[16px] items-center">
                        {Faq10 ? (
                          <div
                            className="w-[10%] bg-[#ff0000] p-2 h-[20%] text-center text-white font-bold cursor-pointer"
                            onClick={() => setFaq10(false)}
                          >
                            -
                          </div>
                        ) : (
                          <div
                            className="w-[10%] bg-[#ff0000] p-2 h-[20%] text-center text-white font-bold cursor-pointer "
                            onClick={() => {
                              setFaq6(false),
                                setFaq7(false),
                                setFaq8(false),
                                setFaq9(false),
                                setFaq10(true);
                            }}
                          >
                            +
                          </div>
                        )}
                        <div className="">What is a Pay-Out Schedule?</div>
                      </div>

                      {Faq10 ? (
                        <div className="flex  border-t-2 pt-3">
                          <div className="px-8 font-normal text-[16px] font-sans text-[#212529]">
                            Car rentals will be paid within 10-20 days. However,
                            MyridePay may hold the amount for a longer period,
                            including but not limited to a proprietary set of
                            rules, chargeback rates, transaction behaviour, and
                            other supplemental data about your business.
                          </div>
                        </div>
                      ) : (
                        " "
                      )}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </Container>
        </div>
        {/*======================================================== Create Your Online Payments Account Now======================================== */}
        <div className="from-[#25252517]   bg-background1 bg-center bg-cover bg-no-repeat mt-8 ">
          <Container className="">
            <div className="md:flex justify-between text-white  xs:p-11 p-7">
              <div className="md:w-[50%] w-full mt-5 mb-2">
                <div>
                  <span className="md:text-[25px] text-[20px] font-bold text-[#FFFFFF] ">
                    Ready to get started?
                  </span>

                  <span className="text-[16px] text-[#FFFFFF] font-sans font-light">
                    <p className="w-[90%]">
                      Apply for the MyRidePay Online Payment Gateway Program
                      online by submitting your details.
                    </p>
                    <p>
                      Our Agent will contact you and guide you through the whole
                      process.
                    </p>
                    <p>
                      Our Agent will contact you and guide you through the whole
                      process.
                    </p>
                  </span>
                </div>

                <div className="mt-8">
                  <span className="md:text-[25px] text-[20px] font-bold text-[#FFFFFF]">
                    Onboarding
                  </span>

                  <p className="mt-3 text-[16px] text-[#FFFFFF] font-sans font-light ">
                    We will assess your credentials and request for relevant
                    documentation, to assess the eligibility. Within 24 to 48
                    hours we will confirm your account, and you can take the
                    test tour or simply go live by integrating our payment
                    portal.
                  </p>
                </div>

                <div className="mt-8">
                  <span className="md:text-[25px] text-[20px] font-bold text-[#FFFFFF]">
                    Integration
                  </span>

                  <p className="mt-3 text-[16px] text-[#FFFFFF] font-sans font-light">
                    It is time to integrate our payment solutions on your car
                    rental website and start receiving your payments through a
                    secure, easier and faster method.
                  </p>
                </div>
              </div>

              <div className=" md:w-[50%] w-full mt-5 ">
                <p className="md:text-center font-semibold font-raleway  text-[20px]">
                  Create Your Online Payments Account Now
                </p>

                <div className="  grid  md:grid-cols-2 grid-cols-1 justify-between gap-4 md:ml-4 mt-5 text-[#7A8489]">
                  <input
                    type="text"
                    required
                    placeholder="Company Name*"
                    className="focus:outline-0 focus:border:none w-full  p-2"
                  />

                  <input
                    type="text"
                    required
                    placeholder="Contact Person*"
                    className="focus:outline-0  w-full p-2 md:mt-0 mt-3"
                  />
                </div>

                <div className="  grid  md:grid-cols-2 grid-cols-1 justify-between  gap-1 md:ml-4 md:mt-5 mt-3 w-full text-[#7A8489]">
                  <input
                    type="text"
                    required
                    placeholder="Contact Number*"
                    className="focus:outline-0 md:w-[96%] md:mt-0 mt-3  p-2"
                  />

                  <select
                    name="Number of Cars*"
                    id="cars"
                    required
                    className=" p-2 md:w-[95%] w-full md:mt-0 mt-4 focus:outline-0  "
                  >
                    <option value="volvo">Number of Cars*</option>
                    <option value="saab">(1-10)</option>
                    <option value="mercedes">(11-30)</option>
                    <option value="audi">(31-50)</option>
                    <option value="audi">(50+)</option>
                  </select>
                </div>

                <div className="bg-[#4f504d] md:w-[240px] w-[80%] px-[14px] py-[15px] text-center sm:text-[16px] text-[12px] font-sans rounded mt-8 md:ml-32 sm:ml-10 ml-4 cursor-pointer">
                  REQUEST A CALL BACK
                </div>

                <div className="flex gap-3 md:visible  invisible mt-5 ml-14">
                  <div className="w-[163px]">
                    <Image
                      src="./onlineRegistration.svg"
                      fill
                      className="custom_img"
                    />
                  </div>

                  <div className="w-[163px]">
                    <Image
                      src="/getApplication.webp"
                      fill
                      className="custom_img"
                    />
                  </div>
                  <div className="w-[163px]">
                    <Image
                      src="/RecevingPayments.webp"
                      fill
                      className="custom_img"
                    />
                  </div>
                </div>
              </div>
            </div>
          </Container>
        </div>
        {/*===================================================== Our Service Provider======================================= */}
        <div className="w-full mt-8    ">
          <div className="text-center md:text-4xl text-[16px] font-sans font-normal text-[#7c7c7c] p-4 ">
            Our Service Provider
          </div>
          {/* <div className="md:flex lg:gap-2 md:gap-2  mt-5">
            <div className="bg-[#e9e9e9]   md:w-[448px] h-[188px]  w-full  p-3">
              <div className="text-center mt-1 md:text-2xl xs:text-[24px] text:sm text-[#212529] font-raleway font-semibold">
                Banking Service Provider
              </div>

              <div className="md:flex lg:w-full md:w-[220px] w-[160px] md:mt-10 mt-4 md:gap-5 xs:gap-2 gap-0">
                <div className="relative md:w-[204px] xs:w-[350px] w-[120px] h-[42px] md:ml-8 sm:ml-[100px] xs:ml-[60px] ml-[100px]  ">
                  <Image
                    src="emirats.svg"
                    alt="emirat"
                    fill
                    className="custom_img"
                  />
                </div>

                <div className="relative md:mt-0 mt-7  md:w-[204px] xs:w-[350px] w-[120px] pb-1 h-[42px] md:ml-8 sm:ml-[90px] xs:ml-[60px] ml-[100px]">
                  <Image
                    src="east.svg"
                    alt="east"
                    fill
                    className="custom_img"
                  />
                </div>
              </div>
            </div>

            <div className="bg-[#e9e9e9] md:w-[448px] h-[188px]  w-full p-6  md:p-3  md:mt-0 mt-5">
              <div className="text-center mt-1 md:text-2xl xs:text-[24px] text-sm text-[#212529] font-raleway font-semibold ">
                Payment Gateway Provider
              </div>

              <div className=" sm:w-[160px] xs:w-[170px] w-[120px] xs:h-[45px] h-[35px] mt-10 lg:ml-24 md:ml-5 sm:ml-[250px]  ml-[80px]">
                <Image
                  src="/paytab.webp"
                  alt="emirat"
                  fill
                  className="custom_img"
                />
              </div>
            </div>

            <div className="bg-[#e9e9e9] md:w-[448px]  w-full p-6 md:mt-0 mt-5  md:p-3">
              <div className="text-center mt-1 md:text-2xl xs:text-[24px] text:sm text-[#212529] font-raleway font-semibold">
                Technology Provider
              </div>

              <div className=" md:w-[160px] xs:w-[170px] w-[120px] md:h-[40px] h-[25px] mt-10 lg:ml-24 md:ml-6  ml-[100px]">
                <Image
                  src="/Techbay.webp"
                  alt="techbay"
                  fill
                  className="custom_img"
                />
              </div>
            </div>
                </div> */}
          <div className="grid md:grid-cols-3 grid-cols-1 gap-5 md:flex-row flex-col">
            <div className="bg-[#e9e9e9] p-10 gap-5 flex flex-col items-center justify-center">
              <div className=" 2xl:text-2xl lg:text-xl md:text-lg text-base  text-[#212529] font-raleway font-semibold">
                Banking Service Provider
              </div>

              <div className=" grid md:grid-cols-2 grid-cols-1 gap-5">
                <div className="">
                  <Image
                    src="emirats.svg"
                    alt="emirat"
                    fill
                    className="custom_img"
                  />
                </div>

                <div className="">
                  <Image
                    src="east.svg"
                    alt="east"
                    fill
                    className="custom_img"
                  />
                </div>
              </div>
            </div>

            <div className="bg-[#e9e9e9] p-10 gap-5 flex flex-col items-center justify-center">
              <div className=" 2xl:text-2xl lg:text-xl md:text-lg text-base  text-[#212529] font-raleway font-semibold">
                Payment Gateway Provider
              </div>
              <div>
                <Image
                  src="/paytab.webp"
                  alt="paytab"
                  fill
                  className="custom_img"
                />
              </div>
            </div>

            <div className="flex flex-col items-center justify-between gap-5 p-10 bg-[#e9e9e9]">
              <div className=" 2xl:text-2xl lg:text-xl md:text-lg text-base  text-[#212529] font-raleway font-semibold">
                Technology Provider
              </div>
              <div>
                <Image
                  src="/Techbay.webp"
                  alt="techbay"
                  fill
                  className="custom_img"
                />
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
