import Head from "next/head";
import Image from 'next/image'
import { Inter } from "@next/font/google";
//import styles from '@/styles/Home.module.css'
import Container from "@/components/ui/Container";
import { useState } from "react";
import Sliderr from "@/components/ui/Sliderr";
import Slider1 from "@/components/ui/Slider1";
//import YouTube from "react-youtube";
const inter = Inter({ subsets: ["latin"] });




export default function Home() {
  const [Faq1, setFaq1] = useState(false);
  const [Faq2, setFaq2] = useState(false);
  const [Faq3, setFaq3] = useState(false);
  const [Faq4, setFaq4] = useState(false);
  const [Faq5, setFaq5] = useState(false);
  const [Faq6, setFaq6] = useState(false);
  const [Faq7, setFaq7] = useState(false);
  const [Faq8, setFaq8] = useState(false);
  const [Faq9, setFaq9] = useState(false);
  const [Faq10, setFaq10] = useState(false);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.icon" />
      </Head>
      <main>
        <div className="  w-full bg-pink-50">
         
            <div className=" w-full md:flex   ">
         
              <div className="w-[50%]">
              <div className="w-full">
                <Image src="/poster1.png" fill alt="poster" className="custom_img"/>
              </div>
              </div>

              
              <div className="w-[50%] ">
                <iframe
                  src="https://www.youtube.com/embed/pxOu8gO5mTI"
                  frameborder="0"
                  allow="accelerometer; autoplay"
                  // clipboard-write
                  encrypted-media="true"
                  // gyroscope
                  picture-in-picture
                  web-share
                  allowFullScreen
                  className="custom_img"
                />
              </div>
            </div>
         

        </div>
        {/*==========================================Smartest Payment Gateway for Car Rentals ==================================== */}

        <div className=" w-full h-[30%] mt-[20px] bg-background bg-center bg-cover bg-no-repeat">
          <Container>
            <div className="text-center md:ml-0 ml-2 pl-7 text-4xl font-semibold">
              Smartest Payment Gateway for
              <span className="text-red-600"> Car Rentals</span>
            </div>

            <div className=" w-full flex justify-between ml-0  py-5">
              <div className="gap-4">
                <div className="w-[223px]  ">
                  <Image src="./onlineRegistration.svg" fill className="custom_img" />
                </div>
                <div className="text-center ">Sign Up for Free</div>
              </div>
              <div className=" gap-4 ">
                <div className="w-[223px] ">
                  <Image src="/getApplication.webp" fill className="custom_img"  />
                </div>
                <div className="text-center ">
                  Get Application Approval <br/> within 24 hours
                </div>

                <div className="bg-[#ff0000] items-center  my-3  text-white hover:text-[#ff0000] hover:bg-white hover:border border-2  border-[#ff0000] w-20 rounded p-2 text-center mt-5 ml-[26%]">
                  <span className=" ">Sign Up</span>
                </div>
              </div>

              <div className="gap-4">
                <div className=" w-[223px] ">
                  <Image src="/RecevingPayments.webp" fill className="custom_img" />
                </div>
                <div className="text-center mt-2">Start Receiving Payments</div>
              </div>
            </div>
          </Container>
        </div>

        {/*============================================================== SLIDER ===================================== */}

        <div className="mt-5 ">
          <Slider1 />
        </div>

        {/*=============================================== content ===================================================*/}
        <div className="mt-8">
          <Container>
            <div>
              <div className="md:flex gap-5">
                <div className="md:w-[50%] w-full">
                  <span className="text-2xl text-[#4f504d] font-semibold">
                    Going Global?
                  </span>
                  <p className=" text-2xl text-[#4f504d] font-semibold">
                    We got your business covered
                  </p>
                  <span className="w-10 text-[#4f504d] text-base">
                    With MyridePay, geography will be history. To cater to
                    online businesses with global reach, our secure and seamless
                    global payment gateway can support customers by facilitating
                    payments through multiple payment options like American
                    Express, MasterCard, Visa, mada, SADAD, STC Pay, OmanNet and
                    many more.
                  </span>
                </div>

                <div className=" w-[50%] md:flex  flex-col  md:w-[50%] w-full mt-8 md:ml-0 sm:ml-44 ml-24">
                  <div className="md:flex md:gap-5 gap-10 justify-between ">
                    <div className="md:flex gap-2">
                      <Image
                        src="./Tick.svg"
                        alt="tick"
                        width={20}
                        height={10}
                        className="relative  md:ml-0 ml-20 "
                      />
                      Easy Monthly Installments
                    </div>
                    <div className="md:flex gap-2">
                      <Image
                        src="./Tick.svg"
                        alt="tick"
                        width={20}
                        height={10}
                        className="relative  md:ml-0 ml-20 md:mt-0 mt-4"
                      />
                      <span className="md:ml-0 ml-4">Payment Tokenization</span>
                    </div>
                  </div>
                  <div className="md:flex justify-between md:gap-5 gap-10 md:mt-14 ">
                    <div className="md:flex gap-2">
                      <Image
                        src="./Tick.svg"
                        alt="tick"
                        width={20}
                        height={10}
                        className="relative  md:ml-0 ml-20 md:mt-0 mt-4"
                      />
                      <span className="md:ml-0 ml-11">Subscriptions</span>
                    </div>
                    <div className="md:flex gap-2">
                      <Image
                        src="./Tick.svg"
                        alt="tick"
                        width={20}
                        height={10}
                        className="relative  md:ml-0 ml-20 md:mt-0 mt-4"
                      />
                      <span className="md:ml-0 ml-7">Recurring Payments</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </Container>
        </div>
        {/*=================================== Platform to Align Your Car Rental Collections Once and For All============================ */}
        <div className="w-full h-auto mt-5">
          <Container>
            <div className="w-full  md:flex flex-shrink-0  md:gap-7 gap-0 mt-5">
              <div className="md:w-[50%] w-full  ">
                <span className="text-2xl text-center  md:text-left text-[#4f504d] font-semibold">
                  Platform to Align Your Car Rental Collections Once and For All
                </span>

                <div className="text-[#4f504d] font-normal md:text-left text-center">
                  In any business platform, secure payments are the biggest
                  concern. Car rental industry in UAE has vast prospects, and
                  with that comes a concern to keep an established payment
                  gateway for the renters all around the world. MyRide being the
                  devotees for cars wanted an easy process of receiving,
                  converting and tracking the payments received by the renters
                  all around the world. Hence, MyRidePay was born. So no matter
                  what kind of car rental industry you have, let us handle your
                  payment gateway and be free of excessive processes to handle
                  the payments.
                </div>
              </div>
               <div className="w-[50%] pl-[13%]">
              <div className=" w-[288px] h-[310px]  ">
                <Image src="/carCollction.webp" alt="car" fill className="custom_img" />
              </div>
              </div>
            </div>
          </Container>
        </div>
        {/*============================== Why Choose MyRidePay for a Car Rental Gateway? =================================*/}
        <div className="md:flex  w-full h-auto mt-5 pb-4">
          <Container>
            <div className="  w-full md:flex md:flex-shrink-0  md:gap-7  mt-5">
            <div className="w-[50%]">
              <div className=" lg:mt-0 md:mt-44 mt-3 md:ml-0 ml-4 flex-shrink-0  md:w-[511px] w-[350px] md:h-[507px] h-[380px]">
                <Image src="/chooseUs.webp" alt="tick" fill className="custom_img" />
              </div>
</div>
              <div className=" w-[50%] md:text-left text-center md:p-0 p-4 ">
                <span className="md:text-2xl text-lg text-[#4f504d] font-semibold">
                  Why Choose MyRidePay for a Car Rental Gateway?
                </span>

                <div>
                  To provide car rental companies with the most secure payment
                  gateway, we have partnered with PayTabs. PayTabs is one of the
                  leading payment gateway providers for every industry. Our
                  years of experience in the automobile industry and PayTabs
                  experience combined can solve all of your payment problems.
                  <li>
                    Accept payments from anywhere in the world with multiple
                    alternative payment options, our payment gateway makes car
                    rental for your customers hassle-free which subsequently
                    helps you to grow your business.
                  </li>
                  <li>
                    Payment security and fraud prevention are the main focus of
                    this venture. We keep your customers data secure, so they
                    can rely on you for your services.
                  </li>
                  <li>
                    Boost your processing speed with this payment platform, more
                    reliability and better acceptance rates.
                  </li>
                  <li>
                    You will have a personal and dedicated account team and live
                    transaction monitoring option for closer accessibility.
                  </li>
                  <li>
                    Simple website integrations with API solutions, SDK, HTTPS
                    redirection and secure hosting.
                  </li>
                  <li>
                    Quickly receive access to the amount paid by your customers.
                  </li>
                  <li>
                    Accept payments securely and immediately via Visa and
                    Mastercard and we will settle your sales automatically to
                    your bank account.
                  </li>
                  <div className=" md:pb-5  bg-[#bf0000] text-white md:text-base text-sm font-bold text-center md:w-[50%] w-[90%] md:ml-0 ml-3 p-2 rounded mt-6 ">
                    Checkout Our Awesome Packages
                  </div>
                </div>
              </div>
            </div>
          </Container>
        </div>
        {/*================================================== Services Slider ============================================ */}

        <div className="mt-8 w-full ">
          <p className="text-center text-4xl text-[] ">Services</p>
          <div className="mt-8 md:ml-24 ml-5 ">
            <Sliderr />
          </div>
        </div>

        {/*================================================== FAQs =================================================== */}
        <div className=" mt-8 ">
          <Container>
            <div className="w-full justify-between  ">
              <span className="text-4xl ">FAQs</span>
              <div className="md:flex justify-between w-full mt-5">
                <div className="md:w-[50%] w-full bg-gray-100">
                  <div className="bg-white ">
                    <div className="flex gap-3">
                      <div
                        className="w-[10%] bg-red-600 p-2 h-[20%] text-center text-white font-bold cursor-pointer"
                        onClick={() => {
                          setFaq1(true);
                          setFaq2(false);
                          setFaq3(false);
                          setFaq4(false);
                          setFaq5(false);
                        }}
                      >
                        +
                      </div>

                      {/* <div
                          className="w-[10%] bg-red-600 p-2 h-[20%] text-center text-white font-bold cursor-pointer"
                          onClick={() => setFaq1(false)}
                        >
                          -
                        </div> */}

                      <div className="w-[100%]">
                        When Can You Integrate with MyridePay Payment Gateway?
                      </div>
                    </div>
                    <hr />
                    {Faq1 ? (
                      <div className="flex justify-between mt-5">
                        <div
                          className="w-[10%] bg-red-600 p-2 h-[20%] text-center text-white font-bold cursor-pointer"
                          onClick={() => setFaq1(false)}
                        >
                          -
                        </div>
                        <div className="pl-4">
                          MyridePay offers a test before you go live. You can
                          register online and <br /> test our services. Once you
                          are satisfied, you can integrate the gateway and go
                          live.
                        </div>
                      </div>
                    ) : (
                      " "
                    )}
                  </div>
                  <div>
                    <div className="bg-white">
                      <div className="flex  gap-3 mt-5">
                        <div
                          className="w-[10%] bg-red-600 p-2 h-[20%] text-center text-white font-bold cursor-pointer"
                          onClick={() => {
                            setFaq1(false),
                              setFaq2(true),
                              setFaq3(false),
                              setFaq4(false),
                              setFaq5(false);
                          }}
                        >
                          +
                        </div>
                        <div className="">What is a Payment Gateway?</div>
                      </div>
                      <hr />
                      {Faq2 ? (
                        <div className="flex justify-between mt-5">
                          <div
                            className="w-[10%] bg-red-600 p-2 h-[20%] text-center text-white font-bold cursor-pointer"
                            onClick={() => setFaq2(false)}
                          >
                            -
                          </div>
                          <div className="pl-4">
                            Whenever someone makes a payment through their
                            credit card, <br /> the information is sent to the
                            cardholder’s account to check if the <br />
                            transaction is allowed or not. In an E-commerce
                            setting, this process is done <br /> via Payment
                            Gateway. Every company who wishes to accept <br />
                            credit cards require a safe portal through which the
                            transactions can <br />
                            pass. MyridePay offers a secure portal for online
                            payments for car rental companies.
                          </div>
                        </div>
                      ) : (
                        " "
                      )}
                    </div>
                    <div className="bg-white">
                      <div className="flex  gap-3 mt-5">
                        <div
                          className="w-[10%] bg-red-600 p-2 h-[20%] text-center text-white font-bold cursor-pointer"
                          onClick={() => {
                            setFaq1(false),
                              setFaq2(false),
                              setFaq3(true),
                              setFaq4(false),
                              setFaq5(false);
                          }}
                        >
                          +
                        </div>
                        <div className="">
                          How Long Does It Take To Integrate MyridePay Payment
                          Gateway?
                        </div>
                      </div>

                      <hr />
                      {Faq3 ? (
                        <div className="flex justify-between mt-5">
                          <div
                            className="w-[10%] bg-red-600 p-2 h-[20%] text-center text-white font-bold cursor-pointer"
                            onClick={() => setFaq3(false)}
                          >
                            -
                          </div>
                          <div className="pl-4">
                            The integration process of MyridePay Payment Gateway
                            can <br />
                            take anywhere between 24 to 48 hours.
                          </div>
                        </div>
                      ) : (
                        " "
                      )}
                    </div>
                  </div>

                  <div className="bg-white">
                    <div className="flex gap-3  mt-5">
                      <div
                        className="w-[10%] bg-red-600 p-2 h-[20%] text-center text-white font-bold cursor-pointer "
                        onClick={() => {
                          setFaq1(false),
                            setFaq2(false),
                            setFaq2(false),
                            setFaq3(false),
                            setFaq4(true),
                            setFaq5(false);
                        }}
                      >
                        +
                      </div>
                      <div className="">
                        What Do I Need to Start Accepting Credit Cards?
                      </div>
                    </div>

                    <hr />
                    {Faq4 ? (
                      <div className="flex justify-between mt-5">
                        <div
                          className="w-[10%] bg-red-600 p-2 h-[20%] text-center text-white font-bold cursor-pointer"
                          onClick={() => setFaq4(false)}
                        >
                          -
                        </div>
                        <div className="pl-4">
                          You need a working online website for renting cars.
                          Once we <br />
                          have verified your credentials, you will be provided
                          with a <br /> login and password bank account with our
                          affiliated bank.
                        </div>
                      </div>
                    ) : (
                      " "
                    )}
                  </div>

                  <div className="">
                    <div className="bg-white">
                      <div className="flex gap-2 mt-5">
                        <div
                          className="w-[10%] bg-red-600 p-2 h-[20%] text-center text-white font-bold cursor-pointer "
                          onClick={() => {
                            setFaq1(false),
                              setFaq1(false),
                              setFaq2(false),
                              setFaq3(false),
                              setFaq4(false),
                              setFaq5(true);
                          }}
                        >
                          +
                        </div>
                        <div className="text-center">
                          What Kind of Credit/Debit Cards are Accepted?
                        </div>
                      </div>

                      <hr />
                      {Faq5 ? (
                        <div className="flex justify-between mt-5 ">
                          <div
                            className="w-[10%] bg-red-600 p-2 h-[20%] text-center text-white font-bold cursor-pointer"
                            onClick={() => setFaq5(false)}
                          >
                            -
                          </div>
                          <div className="pl-4">
                            You will be able to accept major credit/debit cards
                            from MasterCard, <br /> Visa, American Express* at
                            this moment. We will be adding more card processors
                          </div>
                        </div>
                      ) : (
                        " "
                      )}
                    </div>
                  </div>
                </div>

                {/*=============================================== FAQs 2nd part ===========================================================*/}

                <div className="md:w-[50%] bg-gray-100 w-full md:mt-0 mt-5">
                  <div>
                    <div className="bg-white">
                      <div className="flex gap-3">
                        <div
                          className="w-[10%] bg-red-600 p-2 h-[20%] text-center text-white font-bold cursor-pointer "
                          onClick={() => {
                            setFaq6(true),
                              setFaq7(false),
                              setFaq8(false),
                              setFaq9(false),
                              setFaq10(true);
                          }}
                        >
                          +
                        </div>

                        <div className="">
                          Do I Need Another Software for Credit Card Payments?
                        </div>
                      </div>

                      <hr />
                      {Faq6 ? (
                        <div className="flex mt-5 ">
                          <div
                            className="w-[10%] bg-red-600 p-2 h-[20%] text-center text-white font-bold cursor-pointer"
                            onClick={() => setFaq6(false)}
                          >
                            -
                          </div>
                          <div className="ml-3">
                            Our system works with all the operating <br />
                            systems and mobile operating systems,
                            <br /> so you don’t have to plug in any other
                            software.
                            <br /> Once you have created an account with us, we
                            will provide you <br />
                            with simple coding and you’re done.
                          </div>
                        </div>
                      ) : (
                        " "
                      )}
                    </div>
                  </div>

                  <div>
                    <div className="bg-white">
                      <div className="flex gap-3 mt-5">
                        <div
                          className="w-[10%] bg-red-600 p-2 h-[20%] text-center text-white font-bold cursor-pointer "
                          onClick={() => {
                            setFaq6(false),
                              setFaq7(true),
                              setFaq8(false),
                              setFaq9(false),
                              setFaq10(false);
                          }}
                        >
                          +
                        </div>
                        <div className="">
                          Can I Get Details of the Payments?
                        </div>
                      </div>

                      <hr />
                      {Faq7 ? (
                        <div className="flex mt-5 ">
                          <div
                            className="w-[10%] bg-red-600 p-2 h-[20%] text-center text-white font-bold cursor-pointer"
                            onClick={() => setFaq7(false)}
                          >
                            -
                          </div>
                          <div className="ml-3">
                            Details of transactions are available 24/7 in your
                            account. You can check them anytime.
                          </div>
                        </div>
                      ) : (
                        " "
                      )}
                    </div>
                  </div>

                  <div>
                    <div className="bg-white">
                      <div className="flex gap-3 mt-5">
                        <div
                          className="w-[10%] bg-red-600 p-2 h-[20%] text-center text-white font-bold cursor-pointer "
                          onClick={() => {
                            setFaq6(false),
                              setFaq7(false),
                              setFaq8(true),
                              setFaq9(false),
                              setFaq10(false);
                          }}
                        >
                          +
                        </div>
                        <div className="">
                          What Documents do I require to get a Payment
                          Gateway?an I have multiple activities in a single
                          feature?
                        </div>
                      </div>

                      <hr />
                      {Faq8 ? (
                        <div className="flex  mt-5 ">
                          <div
                            className="w-[10%] bg-red-600 p-2 h-[20%] text-center text-white font-bold cursor-pointer"
                            onClick={() => setFaq8(false)}
                          >
                            -
                          </div>
                          <div className="ml-4">
                            To activate your application, MyridePay requires
                            clear scanned <br /> copy the following documents:
                            <li>
                              Personal IDs issued by the Government of Your Car
                              Rental <br />
                              Business owner and partner(s) if any.
                            </li>
                            <li>
                              Government Issued Business License/Commercial
                              Registration <br />
                              (CR).
                            </li>
                            <li>
                              Company’s Bank Statement (3 months) on the Bank’s
                              official letterhead, <br /> containing complete
                              account information IBAN,
                              <br /> account number, beneficiary name etc.
                            </li>
                            <li>
                              Your logo will be required after signing up when
                              you have started <br /> using the payment gateway.
                            </li>
                            <li>
                              Proof of Address (eg: Rental lease, Electricity
                              Bill)
                            </li>
                            <li>Rental Company’s Terms and Conditions.</li>
                            <li>MOA / if Applicable.</li>
                            Further documentation can be demanded to help
                            demonstrate <br />
                            the financial stability and continuity of the
                            business. Note: Upload clear <br /> copies of the
                            requested documents. State required details as
                            accurately <br /> as possible to avoid delays in the
                            approval process. Contact us <br /> for further
                            assistance.
                          </div>
                        </div>
                      ) : (
                        " "
                      )}
                    </div>
                  </div>

                  <div>
                    <div className="bg-white">
                      <div className="flex gap-3 mt-5">
                        <div
                          className="w-[10%] bg-red-600 p-2 h-[20%] text-center text-white font-bold cursor-pointer "
                          onClick={() => {
                            setFaq6(false),
                              setFaq7(false),
                              setFaq8(false),
                              setFaq9(true),
                              setFaq10(false);
                          }}
                        >
                          +
                        </div>
                        <div className="">
                          Why is My Payment Gateway Taking Long to be Live?
                        </div>
                      </div>

                      <hr />
                      {Faq9 ? (
                        <div className="flex  mt-5 ">
                          <div
                            className="w-[10%] bg-red-600 p-2 h-[20%] text-center text-white font-bold cursor-pointer"
                            onClick={() => setFaq9(false)}
                          >
                            -
                          </div>
                          <div className="ml-3">
                            Here are some reasons for delays in your Account.
                            <li>
                              There is an issue with the validity of the
                              documents.
                            </li>
                            <li>
                              We require additional documentation regarding your
                              establishment.
                            </li>
                            <li>
                              There might be a delay in the bank’s process.
                            </li>
                            <li>The application requires special approval.</li>
                          </div>
                        </div>
                      ) : (
                        " "
                      )}
                    </div>
                  </div>

                  <div>
                    <div className="bg-white">
                      <div className="flex gap-3 mt-5">
                        <div
                          className="w-[10%] bg-red-600 p-2 h-[20%] text-center text-white font-bold cursor-pointer "
                          onClick={() => {
                            setFaq6(false),
                              setFaq7(false),
                              setFaq8(false),
                              setFaq9(false),
                              setFaq10(true);
                          }}
                        >
                          +
                        </div>
                        <div className="">What is a Pay-Out Schedule?</div>
                      </div>

                      <hr />
                      {Faq10 ? (
                        <div className="flex  mt-5 ">
                          <div
                            className="w-[10%] bg-red-600 p-2 h-[20%] text-center text-white font-bold cursor-pointer"
                            onClick={() => setFaq10(false)}
                          >
                            -
                          </div>
                          <div className="ml-3">
                            Car rentals will be paid within 10-20 days. However,
                            MyridePay may hold <br /> the amount for a longer
                            period, including but not limited to a <br />
                            proprietary set of rules, chargeback rates,
                            transaction behaviour, and <br />
                            other supplemental data about your business.
                          </div>
                        </div>
                      ) : (
                        " "
                      )}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </Container>
        </div>
        {/*======================================================== Create Your Online Payments Account Now======================================== */}
        <div className="from-[#25252517] bg-background1 bg-center bg-cover bg-no-repeat mt-8 pl-4">
          <Container className="">
            <div className="md:flex justify-between text-white ">
              <div className="md:w-[50%] w-full mt-5 mb-2">
                <div>
                  <span className="text-[25px] font-bold ">
                    Ready to get started?
                  </span>

                  <p className="mt-3">
                    Apply for the MyRidePay Online Payment Gateway Program
                    online by submitting your details. <br />
                    Our Agent will contact you and guide you through the whole
                    process. Our Agent will contact you and guide you through
                    the whole process.
                  </p>
                </div>

                <div className="mt-8">
                  <span className="text-[25px] font-bold ">Onboarding</span>

                  <p className="mt-3">
                    We will assess your credentials and request for relevant
                    documentation, to assess the eligibility. Within 24 to 48
                    hours we will confirm your account, and you can take the
                    test tour or simply go live by integrating our payment
                    portal.
                  </p>
                </div>

                <div className="mt-8">
                  <span className="text-[25px] font-bold ">Integration</span>

                  <p className="mt-3">
                    It is time to integrate our payment solutions on your car
                    rental website and start receiving your payments through a
                    secure, easier and faster method.
                  </p>
                </div>
              </div>

              <div className=" md:w-[50%] w-full mt-5 ">
                <p className="md:text-center">
                  Create Your Online Payments Account Now
                </p>

                <div className="md:flex gap-4 md:ml-4 mt-5">
                  <input
                    type="text"
                    required
                    placeholder="Company Name*"
                    className="focus:outline:none focus:border:none md:w-full w-[90%] p-2"
                  />

                  <input
                    type="text"
                    required
                    placeholder="Contact Person*"
                    className="focus:outline:none  md:w-full w-[90%] p-2 md:mt-0 mt-3"
                  />
                </div>

                <div className="md:flex  justify-between gap-10 md:ml-4 md:mt-5 mt-3 w-full">
                  <input
                    type="text"
                    required
                    placeholder="Contact Number*"
                    className="focus:outline:none md:w-full w-[90%]  p-2"
                  />

                  <select
                    name="Number of Cars*"
                    id="cars"
                    required
                    className=" p-2 md:w-[560px] w-[90%] md:mt-0 mt-3  text-black"
                  >
                    <option value="volvo">Number of Cars*</option>
                    <option value="saab">(1-10)</option>
                    <option value="mercedes">(11-30)</option>
                    <option value="audi">(31-50)</option>
                    <option value="audi">(50+)</option>
                  </select>
                </div>

                <div className="bg-[#4f504d] font-bold md:w-[40%] w-[80%] text-center p-3 rounded mt-8 md:ml-32 ml-10">
                  REQUEST FOR A CALL BACK
                </div>

                <div className="flex gap-3 md:visible  invisible mt-5 ml-14">
                  <div className="relative md:w-[150px] w-[100px] md:h-[160px] h-[100px]">
                    <Image src="./onlineRegistration.svg" fill />
                  </div>

                  <div className="relative md:w-[150px] w-[100px] md:h-[150px] h-[100px]">
                    <Image src="/getApplication.webp" fill />
                  </div>
                  <div className="relative md:w-[150px] w-[100px] md:h-[150px] h-[100px]">
                    <Image src="/RecevingPayments.webp" fill />
                  </div>
                </div>
              </div>
            </div>
          </Container>
        </div>
        {/*===================================================== Our Service Provider======================================= */}
        <div className="w-full mt-8  ">
          <div className="text-center md:text-4xl text-2xl text-[#4f504d] ">
            Our Service Provider
          </div>
          <div className="md:flex gap-5 mt-5">
            <div className="bg-[#e9e9e9] p-3 md:w-[32%] sm:w-[60%] w-full">
              <div className="text-center text-2xl">
                Banking Service Provider
              </div>

              <div className="flex w-full gap-8">
                <div className="relative w-[200px] h-[100px]">
                  <Image src="emirats.svg" alt="emirat" fill />
                </div>

                <div className="relative w-[200px] h-[100px]">
                  <Image src="east.svg" alt="east" fill />
                </div>
              </div>
            </div>

            <div className="bg-[#e9e9e9] md:w-[32%] sm:w-[60%] w-full p-3  md:mt-0 mt-5">
              <div className="text-center mt-3 text-2xl ">
                Payment Gateway Provider
              </div>

              <div className="relative w-[200px] h-[50px] mt-5 lg:ml-24 md:ml-8 ml-24">
                <Image src="/paytab.webp" alt="emirat" fill />
              </div>
            </div>

            <div className="bg-[#e9e9e9] md:w-[32%] sm:w-[60%] w-full p-3 md:mt-0 mt-5">
              <div className="text-center mt-3 text-2xl">
                Technology Provider
              </div>

              <div className="relative w-[200px] h-[50px] mt-5 lg:ml-24 md:ml-8 ml-24">
                <Image src="/Techbay.webp" alt="emirat" fill />
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
